In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv(r"C:\Users\Owner\Python Classwork\data sources\cars.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Owner\\Python Classwork\\data sources\\cars.csv'

In [ ]:
#Handling Missing values
#step1:Replace '?' with NAN
df['normalized-losses'].replace('?',np.nan,inplace=True)
df['horsepower'].replace('?',np.nan,inplace=True)

In [ ]:
df['normalized-losses']=df['normalized-losses'].astype('float64')
df['horsepower']=df['horsepower'].astype('float64')

In [ ]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy='mean')

In [ ]:
X=df.iloc[:,:-1] #All the cols except last col(features)
y=df.iloc[:,-1]  #all the rows of last col(response)

In [ ]:
#fit nan with mean
X[['normalized-losses','horsepower']]=si.fit_transform(X[['normalized-losses','horsepower']])

In [ ]:
#splitting training and test data
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=1)

In [ ]:
#separating cat columns
cat_col=X.select_dtypes(object).columns
cat_col

for col in cat_col:
    le=LabelEncoder() #le is an object of label encoder
    xtrain[col]=le.fit_transform(xtrain[col])
    xtest[col]=le.transform(xtest[col])

xtrain

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
124          3              122.0    14          1           2             2   
181         -1              122.0    19          1           4             2   
154          0               81.0    19          1           4             0   
53           1              113.0     8          1           3             1   
94           1              128.0    12          1           3             1   
..         ...                ...   ...        ...         ...           ...   
133          2              104.0    17          1           3             1   
137          2              104.0    17          1           3             1   
72           3              142.0     9          1           0             2   
140          2               83.0    18          1           2             0   
37           0              106.0     5          1           2             1   

     engine-location  width  height  engine-type  engine-size  horsepower  \
124                0   66.3    50.2            3          156       145.0   
181                0   66.5    54.1            0          161       156.0   
154                0   63.6    59.1            3           92        62.0   
53                 0   64.2    54.1            3           91        68.0   
94                 0   63.8    54.5            3           97        69.0   
..               ...    ...     ...          ...          ...         ...   
133                0   66.5    56.1            3          121       110.0   
137                0   66.5    56.1            0          121       160.0   
72                 0   70.5    50.8            5          234       155.0   
140                0   63.8    55.7            4          108        73.0   
37                 0   65.2    53.3            3          110        86.0   

     city-mpg  highway-mpg  
124        19           24  
181        19           24  
154        27           32  
53         31           38  
94         31           37  
..        ...          ...  
133        21           28  
137        19           26  
72         16           18  
140        26           31  
37         27           33  

[143 rows x 14 columns]

In [ ]:
#Linear Regression model
lr=LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score
y_pred=lr.predict(xtrain)
r2_score(ytrain,y_pred)

0.8504573774895474

In [ ]:
from sklearn.metrics import r2_score
y_pred=lr.predict(xtest)
r2_score(ytest,y_pred)


0.7965566780397385

In [ ]:
#Regularization
from sklearn.linear_model import Lasso, Ridge

In [ ]:
#ridge regularization
l2=Ridge(0.01) #model of ridge
l2.fit(xtrain,ytrain) #training mode

Ridge(alpha=0.01)

In [ ]:
#testing model
l2.score(xtest,ytest)

l2.coef_

#Inducing different values of error to l2 model
for alpha in range(1,10):
    l2=Ridge(alpha)
    l2.fit(xtrain,ytrain)
    test_score=l2.score(xtest,ytest)
    print('Alpha:',alpha)
    print('Test score:',test_score)
    print('-----------------------')

#after an alpha value of 2, we can observe that there is a small change in the r2 score, therefore ridge with alpha=2 is a good model with an R2 score of 81%


Alpha: 1
Test score: 0.8074518758147273
-----------------------
Alpha: 2
Test score: 0.8110292248150515
-----------------------
Alpha: 3
Test score: 0.8126933383890034
-----------------------
Alpha: 4
Test score: 0.81361486450293
-----------------------
Alpha: 5
Test score: 0.8141745853539419
-----------------------
Alpha: 6
Test score: 0.8145301242133355
-----------------------
Alpha: 7
Test score: 0.8147582608502814
-----------------------
Alpha: 8
Test score: 0.8149010602831951
-----------------------
Alpha: 9
Test score: 0.8149836949253053
-----------------------


In [ ]:
l2=Ridge(50)
l2.fit(xtest,ytest)
l2.coef_

array([ -92.27787374,    2.07432651, -158.3042877 , -160.54349499,
       -118.12366955,  550.97172922,    0.        ,  527.07649229,
        211.46464767,   21.44775947,   81.13356922,   85.38604836,
        -14.26805059,   62.17915791])

In [ ]:
#Final Ridge model 
l2=Ridge(2)
l2.fit(xtrain,ytrain)
l2.coef_

array([ 1.66477241e+02, -8.84331252e-01, -1.94641841e+02, -1.13894088e+03,
       -4.80922921e+02,  1.88121378e+03,  7.76076971e+03,  5.06201386e+02,
        5.02070806e+02,  4.65928529e+02,  1.00154543e+02,  1.04124700e+01,
        2.44076984e+02, -3.27713737e+02])

In [ ]:
#Final Lasso model
l1=Lasso(130)
l1.fit(xtest,ytest)
l1.coef_

array([  -0.        ,   -4.0813863 , -180.83436083,   -0.        ,
         -0.        , 2167.45227523,    0.        ,  664.88872076,
        171.05069745,   -0.        ,   71.49779216,   86.09086666,
         -0.        ,   88.22713844])